package com.sdut.community.mapper;

import com.sdut.community.model.User;
<<<<<<< HEAD
import com.sdut.community.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
=======
import org.apache.ibatis.annotations.*;
>>>>>>> bafc6151b975265c04572e50e92c2faf8724cdd0

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
<<<<<<< HEAD
    long countByExample(UserExample example);
=======
    @Insert("insert into user (name,account_id,token,gmt_create,gmt_modified,avatar_url) " +
            "values (#{name}, #{accountId}, #{token}, #{gmtCreate}, #{gmtModified}, #{avatarUrl})")
    int insert(User user);
>>>>>>> bafc6151b975265c04572e50e92c2faf8724cdd0

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
<<<<<<< HEAD
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 22 21:01:02 CST 2021
     */
    int updateByPrimaryKey(User record);
}
=======
    @Select("select * from user where id=#{id}")
    User findById(@Param("id") Long id);

    /**
     * 避免用户二次添加
     * @param accountId
     * @return
     */
    @Select("select * from user where account_id=#{account_id}")
    User findByAccountId(@Param("account_id") String accountId);

    /**
     * 跟新用户
     * @param dbUser
     */
    @Update("update user set name=#{name}, token=#{token}, gmt_modified=#{gmtModified}, avatar_url=#{avatarUrl} " +
            "where id = #{id}")
    void update(User dbUser);
}
>>>>>>> bafc6151b975265c04572e50e92c2faf8724cdd0
